//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string empID { get; set; }
        public string storeID { get; set; }
        public string password { get; set; }
        public string empname { get; set; }
        public string empaddress { get; set; }
        public string emphone { get; set; }
    }
}
