//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string productname { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> mrp { get; set; }
        public Nullable<System.DateTime> expire { get; set; }
        public Nullable<System.DateTime> mfd { get; set; }
        public string productcode { get; set; }
    }
}
